# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.setWindowModality(QtCore.Qt.NonModal)
        dialog.resize(840, 656)
        dialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.lbl_in_directory = QtWidgets.QLabel(self.splitter)
        self.lbl_in_directory.setMaximumSize(QtCore.QSize(60, 20))
        self.lbl_in_directory.setObjectName("lbl_in_directory")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setBaseSize(QtCore.QSize(1000, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_browse = QtWidgets.QPushButton(self.splitter)
        self.pushButton_browse.setMaximumSize(QtCore.QSize(60, 20))
        self.pushButton_browse.setStyleSheet("")
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.pushButton_close = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        self.pushButton_close.setMinimumSize(QtCore.QSize(60, 20))
        self.pushButton_close.setMaximumSize(QtCore.QSize(60, 20))
        self.pushButton_close.setStyleSheet("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout_4.addWidget(self.splitter)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(dialog)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cr_lbl = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cr_lbl.sizePolicy().hasHeightForWidth())
        self.cr_lbl.setSizePolicy(sizePolicy)
        self.cr_lbl.setMinimumSize(QtCore.QSize(50, 0))
        self.cr_lbl.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cr_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.cr_lbl.setObjectName("cr_lbl")
        self.horizontalLayout_5.addWidget(self.cr_lbl)
        self.horizontalSlider_cr = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_cr.setMaximum(255)
        self.horizontalSlider_cr.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cr.setObjectName("horizontalSlider_cr")
        self.horizontalLayout_5.addWidget(self.horizontalSlider_cr)
        self.spinBox_cr = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_cr.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_cr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_cr.setMaximum(255)
        self.spinBox_cr.setObjectName("spinBox_cr")
        self.horizontalLayout_5.addWidget(self.spinBox_cr)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.limValue_lbl = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limValue_lbl.sizePolicy().hasHeightForWidth())
        self.limValue_lbl.setSizePolicy(sizePolicy)
        self.limValue_lbl.setMinimumSize(QtCore.QSize(50, 0))
        self.limValue_lbl.setMaximumSize(QtCore.QSize(200, 16777215))
        self.limValue_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.limValue_lbl.setObjectName("limValue_lbl")
        self.horizontalLayout_6.addWidget(self.limValue_lbl)
        self.horizontalSlider_limit = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_limit.setMaximum(255)
        self.horizontalSlider_limit.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_limit.setObjectName("horizontalSlider_limit")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_limit)
        self.spinBox_limit = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_limit.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_limit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_limit.setMaximum(255)
        self.spinBox_limit.setObjectName("spinBox_limit")
        self.horizontalLayout_6.addWidget(self.spinBox_limit)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_lbl = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_lbl.sizePolicy().hasHeightForWidth())
        self.cb_lbl.setSizePolicy(sizePolicy)
        self.cb_lbl.setMinimumSize(QtCore.QSize(50, 0))
        self.cb_lbl.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cb_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.cb_lbl.setObjectName("cb_lbl")
        self.horizontalLayout_4.addWidget(self.cb_lbl)
        self.horizontalSlider_cb = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_cb.setMaximum(179)
        self.horizontalSlider_cb.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cb.setObjectName("horizontalSlider_cb")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_cb)
        self.spinBox_cb = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_cb.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_cb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_cb.setMaximum(179)
        self.spinBox_cb.setObjectName("spinBox_cb")
        self.horizontalLayout_4.addWidget(self.spinBox_cb)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.splitter_2 = QtWidgets.QSplitter(dialog)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.lbl_progress_status = QtWidgets.QLabel(self.splitter_2)
        self.lbl_progress_status.setMinimumSize(QtCore.QSize(600, 20))
        self.lbl_progress_status.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_progress_status.setObjectName("lbl_progress_status")
        self.lbl_info = QtWidgets.QLabel(self.splitter_2)
        self.lbl_info.setMinimumSize(QtCore.QSize(150, 20))
        self.lbl_info.setMaximumSize(QtCore.QSize(150, 20))
        self.lbl_info.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lbl_info.setAcceptDrops(False)
        self.lbl_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_info.setObjectName("lbl_info")
        self.horizontalLayout_11.addWidget(self.splitter_2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_initImage = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_initImage.sizePolicy().hasHeightForWidth())
        self.label_initImage.setSizePolicy(sizePolicy)
        self.label_initImage.setFrameShape(QtWidgets.QFrame.Box)
        self.label_initImage.setText("")
        self.label_initImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_initImage.setObjectName("label_initImage")
        self.gridLayout_4.addWidget(self.label_initImage, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_finalImage = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_finalImage.sizePolicy().hasHeightForWidth())
        self.label_finalImage.setSizePolicy(sizePolicy)
        self.label_finalImage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_finalImage.setMouseTracking(False)
        self.label_finalImage.setFrameShape(QtWidgets.QFrame.Box)
        self.label_finalImage.setText("")
        self.label_finalImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_finalImage.setObjectName("label_finalImage")
        self.gridLayout_5.addWidget(self.label_finalImage, 3, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.grBox_left = QtWidgets.QGroupBox(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grBox_left.sizePolicy().hasHeightForWidth())
        self.grBox_left.setSizePolicy(sizePolicy)
        self.grBox_left.setMinimumSize(QtCore.QSize(410, 0))
        self.grBox_left.setMaximumSize(QtCore.QSize(16777215, 110))
        self.grBox_left.setTitle("")
        self.grBox_left.setObjectName("grBox_left")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.grBox_left)
        self.gridLayout_6.setContentsMargins(6, 2, 6, 6)
        self.gridLayout_6.setVerticalSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.chkBox_with_flow = QtWidgets.QCheckBox(self.grBox_left)
        self.chkBox_with_flow.setEnabled(False)
        self.chkBox_with_flow.setMinimumSize(QtCore.QSize(81, 20))
        self.chkBox_with_flow.setMaximumSize(QtCore.QSize(16777215, 20))
        self.chkBox_with_flow.setObjectName("chkBox_with_flow")
        self.gridLayout_6.addWidget(self.chkBox_with_flow, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.grBox_left)
        self.grBox_right = QtWidgets.QGroupBox(dialog)
        self.grBox_right.setMinimumSize(QtCore.QSize(410, 0))
        self.grBox_right.setMaximumSize(QtCore.QSize(16777215, 110))
        self.grBox_right.setTitle("")
        self.grBox_right.setObjectName("grBox_right")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.grBox_right)
        self.gridLayout_7.setContentsMargins(6, 2, 6, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridGroupBox_left = QtWidgets.QGroupBox(self.grBox_right)
        self.gridGroupBox_left.setMinimumSize(QtCore.QSize(0, 100))
        self.gridGroupBox_left.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gridGroupBox_left.setTitle("")
        self.gridGroupBox_left.setObjectName("gridGroupBox_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gridGroupBox_left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_pixel_tag = QtWidgets.QLabel(self.gridGroupBox_left)
        self.lbl_pixel_tag.setMinimumSize(QtCore.QSize(95, 0))
        self.lbl_pixel_tag.setMaximumSize(QtCore.QSize(0, 20))
        self.lbl_pixel_tag.setObjectName("lbl_pixel_tag")
        self.horizontalLayout_13.addWidget(self.lbl_pixel_tag)
        self.lbl_pixel_coordinatesAndValue = QtWidgets.QLabel(self.gridGroupBox_left)
        self.lbl_pixel_coordinatesAndValue.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_pixel_coordinatesAndValue.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_pixel_coordinatesAndValue.setObjectName("lbl_pixel_coordinatesAndValue")
        self.horizontalLayout_13.addWidget(self.lbl_pixel_coordinatesAndValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_Step_Left = QtWidgets.QPushButton(self.gridGroupBox_left)
        self.pushButton_Step_Left.setEnabled(False)
        self.pushButton_Step_Left.setMinimumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Left.setMaximumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Left.setStyleSheet("")
        self.pushButton_Step_Left.setObjectName("pushButton_Step_Left")
        self.horizontalLayout_12.addWidget(self.pushButton_Step_Left)
        self.pushButton_RunImgSeq = QtWidgets.QPushButton(self.gridGroupBox_left)
        self.pushButton_RunImgSeq.setEnabled(True)
        self.pushButton_RunImgSeq.setMinimumSize(QtCore.QSize(60, 25))
        self.pushButton_RunImgSeq.setMaximumSize(QtCore.QSize(60, 25))
        self.pushButton_RunImgSeq.setStyleSheet("")
        self.pushButton_RunImgSeq.setObjectName("pushButton_RunImgSeq")
        self.horizontalLayout_12.addWidget(self.pushButton_RunImgSeq)
        self.pushButton_Step_Right = QtWidgets.QPushButton(self.gridGroupBox_left)
        self.pushButton_Step_Right.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Step_Right.sizePolicy().hasHeightForWidth())
        self.pushButton_Step_Right.setSizePolicy(sizePolicy)
        self.pushButton_Step_Right.setMinimumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Right.setMaximumSize(QtCore.QSize(40, 25))
        self.pushButton_Step_Right.setStyleSheet("")
        self.pushButton_Step_Right.setObjectName("pushButton_Step_Right")
        self.horizontalLayout_12.addWidget(self.pushButton_Step_Right)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_segment_method = QtWidgets.QComboBox(self.gridGroupBox_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_segment_method.sizePolicy().hasHeightForWidth())
        self.cb_segment_method.setSizePolicy(sizePolicy)
        self.cb_segment_method.setMinimumSize(QtCore.QSize(220, 20))
        self.cb_segment_method.setMaximumSize(QtCore.QSize(220, 20))
        self.cb_segment_method.setStyleSheet("")
        self.cb_segment_method.setObjectName("cb_segment_method")
        self.verticalLayout.addWidget(self.cb_segment_method)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout_7.addWidget(self.gridGroupBox_left, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.grBox_right)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Cloud segmentation"))
        self.lbl_in_directory.setText(_translate("dialog", "Image Path:"))
        self.lineEdit.setToolTip(_translate("dialog", "Enter path to image directory."))
        self.pushButton_browse.setText(_translate("dialog", "Browse"))
        self.pushButton_close.setText(_translate("dialog", "Close"))
        self.groupBox_2.setTitle(_translate("dialog", "YCrCr Thresholds"))
        self.cr_lbl.setText(_translate("dialog", "Cr"))
        self.limValue_lbl.setText(_translate("dialog", "Limit"))
        self.cb_lbl.setText(_translate("dialog", "Cb"))
        self.lbl_progress_status.setText(_translate("dialog", "---"))
        self.lbl_info.setText(_translate("dialog", "Info:"))
        self.groupBox_4.setTitle(_translate("dialog", "Initial Image"))
        self.groupBox_3.setTitle(_translate("dialog", "Final Image"))
        self.chkBox_with_flow.setText(_translate("dialog", "Optical Flow"))
        self.lbl_pixel_tag.setText(_translate("dialog", "Pixel Coordinates:"))
        self.lbl_pixel_coordinatesAndValue.setText(_translate("dialog", "#"))
        self.pushButton_Step_Left.setToolTip(_translate("dialog", "Go one image ahead"))
        self.pushButton_Step_Left.setText(_translate("dialog", "<<"))
        self.pushButton_RunImgSeq.setToolTip(_translate("dialog", "Starts or stopps the image slide show."))
        self.pushButton_RunImgSeq.setText(_translate("dialog", "Run"))
        self.pushButton_Step_Right.setToolTip(_translate("dialog", "Go one image back"))
        self.pushButton_Step_Right.setText(_translate("dialog", ">>"))
        self.cb_segment_method.setToolTip(_translate("dialog", "Choos segmentation Method"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())

